### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by gitgt** [DanielAdeniji/timeWindows#1]
Hi. Can you please make EXE file? And write if this is 32-bit or 64-bit utility. Thank you.

**Comment by DanielAdeniji** [comment]
1. Can you please make EXE File

The file is available as an executable.  Please check the timeWindows/microsoft/visualStudio/bin/ folder.
The file name is imeMem.exe

2. Is it 32 or 64 bit
The executable is 32 bit

**Comment by gitgt** [comment]
Thanks. I expected to see those in Releases, so I didn't check.

**Comment by DanielAdeniji** [comment]
Placed in release tag.
